#!/usr/bin/env python3
"""
scripts/report_to_html.py

Convert a SOBERANA benchmark JSON report into a self-contained HTML report with interactive charts (Chart.js).

Usage:
  python scripts/report_to_html.py reports/vllm_humaneval_soberana.json --out reports/vllm_humaneval_soberana.html

Output:
  - Single HTML file with:
    - summary metrics (total_kwh, total_kg_co2, tasks passed/failed)
    - charts: per-task kWh, time-to-first-token, generation time, tokens
    - table with task details (expandable)
"""
from __future__ import annotations
import argparse
import json
from pathlib import Path
from datetime import datetime

HTML_TEMPLATE = """<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>SOBERANA Benchmark Report — {title}</title>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <style>
    body {{ font-family: Inter, Arial, sans-serif; margin: 20px; color: #111; }}
    .header {{ display:flex; gap:20px; align-items:center; justify-content:space-between; }}
    .metrics {{ display:flex; gap:12px; }}
    .card {{ background:#f8fafc; border:1px solid #e2e8f0; padding:12px; border-radius:8px; min-width:160px; }}
    .charts {{ display:flex; flex-wrap:wrap; gap:18px; margin-top:18px; }}
    .chart-card {{ width:48%; min-width:320px; background:#fff; border:1px solid #e6eef6; padding:12px; border-radius:8px; }}
    table {{ border-collapse:collapse; width:100%; margin-top:16px; }}
    th,td {{ border:1px solid #e2e8f0; padding:8px; text-align:left; }}
    .passed {{ color:green; font-weight:700; }}
    .failed {{ color:red; font-weight:700; }}
    .footer {{ margin-top:20px; font-size:0.9rem; color:#444; }}
  </style>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
  <div class="header">
    <div>
      <h1>SOBERANA Benchmark Report</h1>
      <div>Model: <strong>{model}</strong> — Generated: <strong>{timestamp}</strong></div>
    </div>
    <div class="metrics">
      <div class="card"><div><small>Total kWh</small></div><div><strong>{total_kwh:.4f}</strong></div></div>
      <div class="card"><div><small>Total kg CO2e</small></div><div><strong>{total_kg_co2:.4f}</strong></div></div>
      <div class="card"><div><small>Tasks</small></div><div><strong>{num_tasks}</strong></div></div>
      <div class="card"><div><small>Passed</small></div><div><strong class="passed">{num_passed}</strong></div></div>
      <div class="card"><div><small>Failed</small></div><div><strong class="failed">{num_failed}</strong></div></div>
    </div>
  </div>

  <div class="charts">
    <div class="chart-card">
      <canvas id="chart_kwh"></canvas>
    </div>
    <div class="chart-card">
      <canvas id="chart_ttft"></canvas>
    </div>
    <div class="chart-card">
      <canvas id="chart_gen_time"></canvas>
    </div>
    <div class="chart-card">
      <canvas id="chart_tokens"></canvas>
    </div>
  </div>

  <h2>Task details</h2>
  <table>
    <thead><tr><th>Task</th><th>Passed</th><th>ttft (s)</th><th>gen_time (s)</th><th>tokens</th><th>kWh</th><th>kgCO2</th></tr></thead>
    <tbody>
      {rows}
    </tbody>
  </table>

  <div class="footer">
    <div>Report generated by IA LIBRE 2026 — <small>{generated_at}</small></div>
  </div>

<script>
const labels = {labels_json};
const data_kwh = {kwh_json};
const data_ttft = {ttft_json};
const data_gen = {gen_json};
const data_tokens = {tokens_json};

function makeChart(ctx, label, data, color) {{
  return new Chart(ctx, {{
    type: 'bar',
    data: {{
      labels: labels,
      datasets: [{{
        label: label,
        data: data,
        backgroundColor: color,
        borderColor: color,
        borderWidth: 1
      }}]
    }},
    options: {{
      responsive: true,
      plugins: {{
        legend: {{ display: false }}
      }},
      scales: {{
        y: {{ beginAtZero: true }}
      }}
    }}
  }});
}}

document.addEventListener('DOMContentLoaded', () => {{
  makeChart(document.getElementById('chart_kwh').getContext('2d'), 'kWh per task', data_kwh, 'rgba(54,162,235,0.7)');
  makeChart(document.getElementById('chart_ttft').getContext('2d'), 'Time to first token (s)', data_ttft, 'rgba(255,159,64,0.7)');
  makeChart(document.getElementById('chart_gen_time').getContext('2d'), 'Generation time (s)', data_gen, 'rgba(75,192,192,0.7)');
  makeChart(document.getElementById('chart_tokens').getContext('2d'), 'Tokens', data_tokens, 'rgba(153,102,255,0.7)');
}});
</script>

</body>
</html>
"""

def build_rows(tasks):
    rows_html = []
    for t in tasks:
        passed = t.get("exec_passed", False) or t.get("passed", False)
        cls = "passed" if passed else "failed"
        ttft = t.get("gpu_monitor", {}).get("duration_s") if t.get("gpu_monitor") else t.get("metrics", {}).get("ttft_s")
        gen_time = t.get("metrics", {}).get("gen_time_s") or t.get("completion_elapsed_s") or t.get("metrics", {}).get("gen_time")
        tokens = t.get("metrics", {}).get("tokens") or t.get("tokens") or 0
        kwh = t.get("kwh") or t.get("metrics", {}).get("kwh") or 0.0
        kg = t.get("kg_co2") or (kwh * float(0.4))
        rows_html.append(f"<tr><td>{t.get('task_id')}</td><td class='{cls}'>{passed}</td><td>{ttft:.4f}</td><td>{gen_time:.4f}</td><td>{tokens}</td><td>{kwh:.6f}</td><td>{kg:.6f}</td></tr>")
    return "\n".join(rows_html)

def main():
    p = argparse.ArgumentParser()
    p.add_argument("json_report", type=str, help="Path to SOBERANA JSON report")
    p.add_argument("--out", "-o", default=None, help="Output HTML path (defaults to same name .html)")
    args = p.parse_args()

    rpt_path = Path(args.json_report)
    if not rpt_path.exists():
        print("Report not found:", rpt_path); return
    data = json.loads(rpt_path.read_text(encoding="utf-8"))

    tasks = data.get("tasks", [])
    labels = [t.get("task_id") for t in tasks]
    kwhs = [t.get("kwh") or t.get("metrics", {}).get("kwh") or 0.0 for t in tasks]
    ttfts = [ (t.get("metrics", {}).get("ttft_s") or 0.0) for t in tasks ]
    gents = [ (t.get("metrics", {}).get("gen_time_s") or t.get("completion_elapsed_s") or 0.0) for t in tasks ]
    tokens = [ (t.get("metrics", {}).get("tokens") or t.get("tokens") or 0) for t in tasks ]

    rows_html = build_rows(tasks)

    html = HTML_TEMPLATE.format(
        title=rpt_path.stem,
        model=data.get("model_path") or data.get("model") or "unknown",
        timestamp=data.get("timestamp_utc") or datetime.utcnow().isoformat()+"Z",
        total_kwh=float(data.get("total_kwh") or data.get("total_kwh", 0.0)),
        total_kg_co2=float(data.get("total_kg_co2") or 0.0),
        num_tasks=len(tasks),
        num_passed=int(data.get("summary", {}).get("num_passed") or sum(1 for t in tasks if t.get("exec_passed") or t.get("passed"))),
        num_failed=int(data.get("summary", {}).get("num_failed") or sum(1 for t in tasks if not (t.get("exec_passed") or t.get("passed")))),
        rows=rows_html,
        generated_at=datetime.utcnow().isoformat()+"Z",
        labels_json=json.dumps(labels),
        kwh_json=json.dumps(kwhs),
        ttft_json=json.dumps(ttfts),
        gen_json=json.dumps(gents),
        tokens_json=json.dumps(tokens),
    )

    out_path = Path(args.out) if args.out else rpt_path.with_suffix(".html")
    out_path.write_text(html, encoding="utf-8")
    print("HTML report created:", out_path)

if __name__ == "__main__":
    import argparse
    main()